--Table creation

-- EMPLOYEES & CUSTOMERS

CREATE TABLE SALESPERSON (
    SalespersonID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(150) NOT NULL,
    Email VARCHAR(150)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE CUSTOMER (
    CustomerID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(150) NOT NULL,
    Address VARCHAR(255),
    Email VARCHAR(150),
    Phone VARCHAR(50),
    SalespersonID INT,
    FOREIGN KEY (SalespersonID) REFERENCES SALESPERSON(SalespersonID)
        ON UPDATE CASCADE
        ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- PRESS & PAPER

CREATE TABLE PRESS (
    PressID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(150) NOT NULL,
    MaxSheetSizeWidth DECIMAL(10,2),
    MaxSheetSizeHeight DECIMAL(10,2),
    MaxStockWeight DECIMAL(10,2),
    MaxSpeed INT,
    ColorBW ENUM('color','bw'),
    InlineOps VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE PAPER_TYPE (
    StockTypeID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Description VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE PAPER (
    PaperID INT AUTO_INCREMENT PRIMARY KEY,
    Weight VARCHAR(50),
    Brand VARCHAR(150),
    StockTypeID INT,
    Color VARCHAR(100),
    Finish VARCHAR(100),
    FOREIGN KEY (StockTypeID) REFERENCES PAPER_TYPE(StockTypeID)
        ON UPDATE CASCADE
        ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- JOBS & INVOICES

CREATE TABLE STATUS (
    StatusID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Description VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE JOB (
    JobID INT AUTO_INCREMENT PRIMARY KEY,
    CustomerID INT NOT NULL,
    SalespersonID INT,
    StatusID INT,
    JobDate DATE,
    FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (SalespersonID) REFERENCES SALESPERSON(SalespersonID)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    FOREIGN KEY (StatusID) REFERENCES STATUS(StatusID)
        ON UPDATE CASCADE
        ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE INVOICE (
    InvoiceID INT AUTO_INCREMENT PRIMARY KEY,
    JobID INT NOT NULL,
    InvoiceDate DATE,
    Amount DECIMAL(10,2),
    PaidStatus ENUM('unpaid','paid','partial') DEFAULT 'unpaid',
    FOREIGN KEY (JobID) REFERENCES JOB(JobID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


-- ITEM & FINISHING

CREATE TABLE PRINT_ITEM_TYPE (
    PrintTypeID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE FINISHING_OPTION (
    OptionID INT AUTO_INCREMENT PRIMARY KEY,
    OptionName VARCHAR(150) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ITEM (
    ItemID INT AUTO_INCREMENT PRIMARY KEY,
    JobID INT NOT NULL,
    PrintTypeID INT NOT NULL,
    PressID INT,
    PaperID INT,
    Width DECIMAL(10,2),
    Height DECIMAL(10,2),
    Quantity INT NOT NULL,
    PageCount INT,
    SimplexDuplex ENUM('simplex','duplex'),
    ColorBW ENUM('color','bw'),
    FOREIGN KEY (JobID) REFERENCES JOB(JobID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (PrintTypeID) REFERENCES PRINT_ITEM_TYPE(PrintTypeID)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    FOREIGN KEY (PressID) REFERENCES PRESS(PressID)
        ON UPDATE CASCADE
        ON DELETE SET NULL,
    FOREIGN KEY (PaperID) REFERENCES PAPER(PaperID)
        ON UPDATE CASCADE
        ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE ITEM_FINISHING (
    ItemID INT NOT NULL,
    OptionID INT NOT NULL,
    PRIMARY KEY (ItemID, OptionID),
    FOREIGN KEY (ItemID) REFERENCES ITEM(ItemID)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    FOREIGN KEY (OptionID) REFERENCES FINISHING_OPTION(OptionID)
        ON UPDATE CASCADE
        ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;